"""Main entry point for the AI Developer Workflow Orchestrator.

This CLI application automates repetitive actions between development
tools such as Freebuff, VS Code, Brave Browser, Git, GitHub, Render,
and Vercel.

Usage:
    python main.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

# Ensure the project root is on sys.path for imports
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config import config_manager, ConfigurationManager
from modules.logger import setup_logger, logger
from modules.terminal import run_command
from modules.clipboard import copy_to_clipboard
from modules.browser import (
    open_url,
    open_github,
    open_render,
    open_render_logs,
    open_vercel,
    open_vercel_deployment,
)
from modules.vscode import open_vscode
from modules.github import auto_commit_and_push, git_status
from modules.render import open_dashboard as render_open_dashboard
from modules.render import open_logs as render_open_logs
from modules.vercel import open_dashboard as vercel_open_dashboard
from modules.vercel import open_deployment as vercel_open_deployment
from modules.prompts import load_template, format_prompt

HISTORY_FILE = PROJECT_ROOT / "data" / "history.json"


# ---------------------------------------------------------------------------
# History helpers
# ---------------------------------------------------------------------------


def load_history() -> list[dict[str, Any]]:
    """Load the execution history from the JSON file.

    Returns:
        list[dict]: List of history entries, newest first.
    """
    if not HISTORY_FILE.exists():
        return []

    try:
        data = HISTORY_FILE.read_text(encoding="utf-8")
        entries: list[dict[str, Any]] = json.loads(data)
        return entries
    except (json.JSONDecodeError, OSError) as exc:
        logger.error("Failed to load history: %s", exc)
        return []


def save_history(entry: dict[str, Any]) -> None:
    """Append an entry to the execution history.

    Args:
        entry: Dictionary with keys like 'timestamp', 'action', 'status'.
    """
    history = load_history()
    history.insert(0, entry)  # newest first

    try:
        HISTORY_FILE.parent.mkdir(parents=True, exist_ok=True)
        HISTORY_FILE.write_text(
            json.dumps(history, indent=2), encoding="utf-8"
        )
    except OSError as exc:
        logger.error("Failed to save history: %s", exc)


def record_action(action: str, status: str, details: str = "") -> None:
    """Record an action in the history log.

    Args:
        action: Description of the action performed.
        status: 'success', 'failure', or 'cancelled'.
        details: Optional additional details about the action.
    """
    entry = {
        "timestamp": datetime.now().isoformat(),
        "action": action,
        "status": status,
        "details": details,
    }
    save_history(entry)


# ---------------------------------------------------------------------------
# Menu display
# ---------------------------------------------------------------------------


def display_menu() -> None:
    """Print the main CLI menu to the console."""
    print("\n" + "=" * 45)
    print("   AI Developer Workflow Orchestrator")
    print("=" * 45)
    print()
    print("  1.  Copy Prompt to Clipboard")
    print("  2.  Open Freebuff")
    print("  3.  Open VS Code")
    print("  4.  Git Push")
    print("  5.  Open GitHub")
    print("  6.  Open Render Dashboard")
    print("  7.  Open Render Logs")
    print("  8.  Open Vercel Dashboard")
    print("  9.  Open Website / Deployment URL")
    print(" 10.  Run Custom Terminal Command")
    print(" 11.  Configuration")
    print(" 12.  Run Full Workflow")
    print(" 13.  View History")
    print(" 14.  Exit")
    print()


# ---------------------------------------------------------------------------
# Menu action handlers
# ---------------------------------------------------------------------------


def action_copy_prompt() -> None:
    """Prompt user for ChatGPT-generated text and copy it to clipboard."""
    print("\n--- Copy Prompt to Clipboard ---")
    print("Paste the prompt generated by ChatGPT (Ctrl+Z then Enter to finish):")
    print()

    lines: list[str] = []
    try:
        while True:
            line = input()
            lines.append(line)
    except EOFError:
        pass

    prompt_text = "\n".join(lines).strip()

    if not prompt_text:
        logger.warning("No prompt text entered.")
        print("⚠  No text entered. Cancelled.")
        return

    if copy_to_clipboard(prompt_text):
        print("✓ Prompt copied to clipboard.")
        record_action("Copy prompt", "success", f"{len(prompt_text)} chars")
    else:
        print("✗ Failed to copy to clipboard.")
        record_action("Copy prompt", "failure")


def action_open_freebuff() -> None:
    """Launch Freebuff using the configured command."""
    print("\n--- Open Freebuff ---")

    freebuff_cmd = config_manager.config.freebuff_command
    if not freebuff_cmd:
        logger.warning("Freebuff command is not configured.")
        print("⚠  Freebuff command is not configured.")
        print("   Set it in Configuration (option 11) or data/config.json.")
        record_action("Open Freebuff", "failure", "command not configured")
        return

    try:
        from modules.terminal import run_command_async

        run_command_async(freebuff_cmd)
        print(f"✓ Freebuff launched: {freebuff_cmd}")
        logger.info("Freebuff launched: %s", freebuff_cmd)
        record_action("Open Freebuff", "success", freebuff_cmd)
    except Exception as exc:
        logger.error("Failed to launch Freebuff: %s", exc)
        print(f"✗ Failed to launch Freebuff: {exc}")
        record_action("Open Freebuff", "failure", str(exc))


def action_open_vscode() -> None:
    """Open VS Code with the configured project directory."""
    print("\n--- Open VS Code ---")

    project_dir = config_manager.config.default_project_directory
    if not project_dir:
        logger.warning("Default project directory is not configured.")
        print("⚠  Default project directory is not configured.")
        print("   Set it in Configuration (option 11) or data/config.json.")

        custom = input("Enter project path (or press Enter to cancel): ").strip()
        if custom:
            project_dir = custom
        else:
            record_action("Open VS Code", "cancelled")
            return

    path = Path(project_dir).expanduser().resolve()
    if open_vscode(path):
        print(f"✓ VS Code opened with project: {path}")
        record_action("Open VS Code", "success", str(path))
    else:
        print("✗ Failed to open VS Code.")
        record_action("Open VS Code", "failure", str(path))


def action_git_push() -> None:
    """Run git commit and push with optional custom message."""
    print("\n--- Git Push ---")

    # Check status first
    state = git_status()
    if state is None:
        print("✗ Not a Git repository or project directory not configured.")
        record_action("Git push", "failure", "not a Git repo or not configured")
        return

    print(f"   Branch: {state.branch}")
    print(f"   Changes: {len(state.untracked_files)} untracked, "
          f"{len(state.modified_files)} modified, {len(state.staged_files)} staged")
    print(f"   Ahead: {state.ahead}, Behind: {state.behind}")

    if not state.has_changes and state.ahead == 0:
        print("\n✓ No changes to push.")
        return

    message = input("\nCommit message (or press Enter for auto-generated): ").strip()
    print()

    if auto_commit_and_push(message or None):
        print("✓ Changes committed and pushed successfully.")
        record_action("Git push", "success", state.branch)
    else:
        print("✗ Git push failed. Check logs for details.")
        record_action("Git push", "failure", state.branch)


def action_open_github() -> None:
    """Open the configured GitHub repository in browser."""
    print("\n--- Open GitHub ---")
    if open_github():
        print("✓ GitHub repository opened in browser.")
        record_action("Open GitHub", "success")
    else:
        print("✗ Failed to open GitHub. Is the URL configured?")
        record_action("Open GitHub", "failure")


def action_open_render() -> None:
    """Open the Render dashboard in browser."""
    print("\n--- Open Render Dashboard ---")
    if render_open_dashboard() or open_render():
        print("✓ Render dashboard opened in browser.")
        record_action("Open Render", "success")
    else:
        print("✗ Failed to open Render. Is the URL configured?")
        record_action("Open Render", "failure")


def action_open_render_logs() -> None:
    """Open the Render logs page in browser."""
    print("\n--- Open Render Logs ---")
    if render_open_logs() or open_render_logs():
        print("✓ Render logs opened in browser.")
        record_action("Open Render Logs", "success")
    else:
        print("✗ Failed to open Render logs. Is the URL configured?")
        record_action("Open Render Logs", "failure")


def action_open_vercel() -> None:
    """Open the Vercel dashboard in browser."""
    print("\n--- Open Vercel Dashboard ---")
    if vercel_open_dashboard() or open_vercel():
        print("✓ Vercel dashboard opened in browser.")
        record_action("Open Vercel", "success")
    else:
        print("✗ Failed to open Vercel. Is the URL configured?")
        record_action("Open Vercel", "failure")


def action_open_website() -> None:
    """Open a deployment URL in browser."""
    print("\n--- Open Website / Deployment URL ---")
    url = input("Enter the website URL: ").strip()

    if not url:
        print("⚠  No URL entered. Cancelled.")
        record_action("Open Website", "cancelled")
        return

    if open_url(url) or vercel_open_deployment(url):
        print(f"✓ Opened: {url}")
        record_action("Open Website", "success", url)
    else:
        print("✗ Failed to open URL.")
        record_action("Open Website", "failure", url)


def action_run_command() -> None:
    """Prompt for and execute a custom terminal command."""
    print("\n--- Run Custom Terminal Command ---")
    command = input("$ ").strip()

    if not command:
        print("⚠  No command entered. Cancelled.")
        return

    print()
    result = run_command(command)

    print("─" * 45)
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)
    print("─" * 45)
    print(f"Exit code: {result.exit_code}")

    record_action("Custom command", "success" if result.success else "failure", command)


def action_configuration() -> None:
    """Open the interactive configuration menu."""
    print("\n--- Configuration ---")
    print("1. View current configuration")
    print("2. Edit configuration interactively")
    print("3. Reset to defaults")
    print()

    choice = input("Select option: ").strip()

    if choice == "1":
        print("\nCurrent Configuration:")
        print("-" * 45)
        cfg = config_manager.config
        print(f"  Brave path:      {cfg.brave_executable_path or '(not set)'}")
        print(f"  VS Code path:    {cfg.vscode_executable_path}")
        print(f"  Project dir:     {cfg.default_project_directory or '(not set)'}")
        print(f"  GitHub URL:      {cfg.github_repository_url or '(not set)'}")
        print(f"  Render URL:      {cfg.render_dashboard_url or '(not set)'}")
        print(f"  Vercel URL:      {cfg.vercel_dashboard_url or '(not set)'}")
        print(f"  Freebuff cmd:    {cfg.freebuff_command or '(not set)'}")
        if cfg.custom:
            print(f"  Custom:          {cfg.custom}")
        print()

    elif choice == "2":
        config_manager.configure_interactive()
        record_action("Configure", "success")

    elif choice == "3":
        confirm = input("Reset all configuration to defaults? (y/N): ").strip().lower()
        if confirm == "y":
            from config import AppConfig
            config_manager._config = AppConfig()
            config_manager.save()
            print("✓ Configuration reset to defaults.")
            record_action("Reset config", "success")
        else:
            print("Cancelled.")

    else:
        print("Invalid option.")


def action_view_history() -> None:
    """Display the execution history."""
    print("\n--- Execution History ---")

    history = load_history()
    if not history:
        print("No history recorded yet.")
        return

    print(f"{'#':<4} {'Timestamp':<22} {'Action':<25} {'Status':<10}")
    print("-" * 65)

    for i, entry in enumerate(history[:20], 1):
        ts = entry.get("timestamp", "?")[:19]
        action = entry.get("action", "?")[:24]
        status = entry.get("status", "?")
        print(f"{i:<4} {ts:<22} {action:<25} {status:<10}")

    if len(history) > 20:
        print(f"\n... and {len(history) - 20} more entries.")
    print()


# ---------------------------------------------------------------------------
# Full workflow
# ---------------------------------------------------------------------------


def run_full_workflow() -> None:
    """Execute the complete AI-assisted coding workflow.

    Steps:
        1. Get task description from the user
        2. Accept ChatGPT-generated prompt and copy it to clipboard
        3. Launch Freebuff
        4. Wait for user confirmation that Freebuff finished
        5. Open VS Code with the project
        6. Run Git commit and push
        7. Open GitHub repository
        8. Open deployment platform (Render / Vercel)
        9. Open the deployed website
        10. Report results
    """
    print("\n" + "=" * 45)
    print("         Full Workflow Execution")
    print("=" * 45)
    print()
    record_action("Workflow started", "success")

    # Step 1: Task description
    print("Step 1/10: Describe the task")
    task = input("What task are you working on? ").strip()
    print()

    # Step 2: ChatGPT prompt
    print("Step 2/10: Paste the ChatGPT-generated prompt")
    print("(Ctrl+Z then Enter to finish)")
    print()

    lines: list[str] = []
    try:
        while True:
            line = input()
            lines.append(line)
    except EOFError:
        pass

    prompt_text = "\n".join(lines).strip()
    if prompt_text:
        copy_to_clipboard(prompt_text)
        print("✓ Prompt copied to clipboard.")
    else:
        print("⚠  No prompt text entered. Skipping clipboard copy.")
    print()

    # Step 3: Launch Freebuff
    print("Step 3/10: Launching Freebuff...")
    freebuff_cmd = config_manager.config.freebuff_command
    if freebuff_cmd:
        try:
            from modules.terminal import run_command_async
            run_command_async(freebuff_cmd)
            print("✓ Freebuff launched.")
        except Exception as exc:
            print(f"⚠  Could not launch Freebuff: {exc}")
    else:
        print("⚠  Freebuff command not configured. Skipping.")
    print()

    # Step 4: Wait for Freebuff completion
    print("Step 4/10: Waiting for Freebuff to complete")
    input("Press Enter after Freebuff has finished generating/modifying code...")
    print("✓ Confirmed.")
    print()

    # Step 5: Open VS Code
    print("Step 5/10: Opening VS Code...")
    project_dir = config_manager.config.default_project_directory
    if project_dir:
        path = Path(project_dir).expanduser().resolve()
        if open_vscode(path):
            print(f"✓ VS Code opened with project: {path}")
        else:
            print("⚠  Could not open VS Code.")
    else:
        print("⚠  Project directory not configured.")
    print()

    # Step 6: Git push
    print("Step 6/10: Checking Git status and pushing changes...")
    state = git_status()
    if state:
        print(f"   Branch: {state.branch}")
        if state.has_changes:
            commit_msg = f"Workflow: {task[:50]}" if task else ""
            if auto_commit_and_push(commit_msg):
                print("✓ Changes committed and pushed.")
            else:
                print("✗ Git push failed. See logs.")
        elif state.ahead > 0:
            auto_commit_and_push()
            print("✓ Pushed pending commits.")
        else:
            print("✓ No new changes to push.")
    else:
        print("⚠  Git status unavailable.")
    print()

    # Step 7: Open GitHub
    print("Step 7/10: Opening GitHub...")
    if open_github():
        print("✓ GitHub repository opened.")
    else:
        print("⚠  GitHub URL not configured.")
    print()

    # Step 8: Open deployment platform
    print("Step 8/10: Opening deployment platform...")
    platform = input("Deployment platform (render/vercel, or press Enter to skip): ").strip().lower()

    if platform == "render":
        if render_open_dashboard() or open_render():
            print("✓ Render dashboard opened.")
        else:
            print("⚠  Render URL not configured.")
    elif platform == "vercel":
        if vercel_open_dashboard() or open_vercel():
            print("✓ Vercel dashboard opened.")
        else:
            print("⚠  Vercel URL not configured.")
    else:
        print("Skipped.")
    print()

    # Step 9: Open deployed website
    print("Step 9/10: Opening the deployed website...")
    deploy_url = input("Deployment URL (or press Enter to skip): ").strip()
    if deploy_url:
        if open_url(deploy_url):
            print(f"✓ Opened: {deploy_url}")
        else:
            print("⚠  Could not open URL.")
    else:
        print("Skipped.")
    print()

    # Step 10: Report
    print("=" * 45)
    print("         Workflow Complete")
    print("=" * 45)
    print(f"   Task: {task or '(not specified)'}")
    print("   Status: ✓ All steps executed")
    print()
    record_action("Workflow completed", "success", task)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """Main entry point. Displays the menu and dispatches user choices."""
    # Ensure logs directory exists
    log_dir = PROJECT_ROOT / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)

    # Re-initialize the root logger with the project-root-aware setup
    setup_logger(
        "workflow_orchestrator",
        log_to_file=True,
        log_to_console=True,
    )

    logger.info("Workflow Orchestrator started.")

    print()
    print("Welcome to the AI Developer Workflow Orchestrator!")
    print("Type a menu number or press Enter to show the menu.")

    while True:
        display_menu()
        choice = input("Select option: ").strip()

        if choice == "1":
            action_copy_prompt()
        elif choice == "2":
            action_open_freebuff()
        elif choice == "3":
            action_open_vscode()
        elif choice == "4":
            action_git_push()
        elif choice == "5":
            action_open_github()
        elif choice == "6":
            action_open_render()
        elif choice == "7":
            action_open_render_logs()
        elif choice == "8":
            action_open_vercel()
        elif choice == "9":
            action_open_website()
        elif choice == "10":
            action_run_command()
        elif choice == "11":
            action_configuration()
        elif choice == "12":
            run_full_workflow()
        elif choice == "13":
            action_view_history()
        elif choice == "14":
            print("\nGoodbye!")
            logger.info("Workflow Orchestrator exited.")
            break
        else:
            print("\nInvalid option. Please enter a number between 1 and 14.")

        print("\n" + "─" * 45)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nExited by user.")
        logger.info("Workflow Orchestrator interrupted by user.")
        sys.exit(0)
    except Exception as exc:
        logger.exception("Unhandled exception: %s", exc)
        print(f"\nAn unexpected error occurred: {exc}")
        sys.exit(1)
