"""FastAPI Backend Server Implementation.
Generated by Antigravity Desktop Worker.
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="E-Learning Research Platform API", version="1.0.0")

class CourseItem(BaseModel):
    id: str
    title: str
    content: str
    quiz_questions: list[str]

@app.get("/health")
def health_check():
    return {"status": "ok", "service": "elearning_api"}

@app.get("/courses")
def list_courses():
    return [{"id": "c1", "title": "Advanced ML Research", "quiz_questions": ["Q1", "Q2"]}]
